### 获取今日ip
GET http://127.0.0.1:5000/get_total_ip
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhcGkubS5jb20iLCJpYXQiOjE1OTM0MzkwNzUsInN1YiI6Img1IiwiYXVkIjoiTW96aWxsYVwvNS4wIChMaW51eDsgQW5kcm9pZCA4LjAuMDsgUGl4ZWwgMiBYTCBCdWlsZFwvT1BEMS4xNzA4MTYuMDA0KSBBcHBsZVdlYktpdFwvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC84My4wLjQxMDMuMTE2IE1vYmlsZSBTYWZhcmlcLzUzNy4zNiIsImV4cCI6MTYyNDk3NTA3NSwidWlkIjoiNWVmOWYzNjNlYzI3MDAwMDkwMDAzYWIyIiwiYWNjb3VudCI6IjE1OTI2OTAwNjUzIn0.aPgUqu0jnsXVcQvD03xobxk446qBQ58rWX0RwXIGKjVCqPMtTjMhrM1q5OY9VPUh_Ue6HG_wxLh4Gq3zGBcmi4xywq8PrHVJZkvH4Yv0Pvw4_yo1MpTkLGrXEpye1TBNe6W13bh1cjPKGuCvk0hH_3NoqtcbN5ayuJOj0eSZNzo
Content-Type: application/x-www-form-urlencoded

### 获取今日ip
GET http://127.0.0.1:5000/get_total_pv
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhcGkubS5jb20iLCJpYXQiOjE1OTM0MzkwNzUsInN1YiI6Img1IiwiYXVkIjoiTW96aWxsYVwvNS4wIChMaW51eDsgQW5kcm9pZCA4LjAuMDsgUGl4ZWwgMiBYTCBCdWlsZFwvT1BEMS4xNzA4MTYuMDA0KSBBcHBsZVdlYktpdFwvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC84My4wLjQxMDMuMTE2IE1vYmlsZSBTYWZhcmlcLzUzNy4zNiIsImV4cCI6MTYyNDk3NTA3NSwidWlkIjoiNWVmOWYzNjNlYzI3MDAwMDkwMDAzYWIyIiwiYWNjb3VudCI6IjE1OTI2OTAwNjUzIn0.aPgUqu0jnsXVcQvD03xobxk446qBQ58rWX0RwXIGKjVCqPMtTjMhrM1q5OY9VPUh_Ue6HG_wxLh4Gq3zGBcmi4xywq8PrHVJZkvH4Yv0Pvw4_yo1MpTkLGrXEpye1TBNe6W13bh1cjPKGuCvk0hH_3NoqtcbN5ayuJOj0eSZNzo
Content-Type: application/x-www-form-urlencoded


### 获取每秒钟的请求数量（pv）
GET http://127.0.0.1:5000/get_request_num_by_secends
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhcGkubS5jb20iLCJpYXQiOjE1OTM0MzkwNzUsInN1YiI6Img1IiwiYXVkIjoiTW96aWxsYVwvNS4wIChMaW51eDsgQW5kcm9pZCA4LjAuMDsgUGl4ZWwgMiBYTCBCdWlsZFwvT1BEMS4xNzA4MTYuMDA0KSBBcHBsZVdlYktpdFwvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC84My4wLjQxMDMuMTE2IE1vYmlsZSBTYWZhcmlcLzUzNy4zNiIsImV4cCI6MTYyNDk3NTA3NSwidWlkIjoiNWVmOWYzNjNlYzI3MDAwMDkwMDAzYWIyIiwiYWNjb3VudCI6IjE1OTI2OTAwNjUzIn0.aPgUqu0jnsXVcQvD03xobxk446qBQ58rWX0RwXIGKjVCqPMtTjMhrM1q5OY9VPUh_Ue6HG_wxLh4Gq3zGBcmi4xywq8PrHVJZkvH4Yv0Pvw4_yo1MpTkLGrXEpye1TBNe6W13bh1cjPKGuCvk0hH_3NoqtcbN5ayuJOj0eSZNzo
Content-Type: application/x-www-form-urlencoded

### 获取每分钟的请求数量（pv）
GET http://127.0.0.1:5000/get_pv_num_by_minute
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhcGkubS5jb20iLCJpYXQiOjE1OTM0MzkwNzUsInN1YiI6Img1IiwiYXVkIjoiTW96aWxsYVwvNS4wIChMaW51eDsgQW5kcm9pZCA4LjAuMDsgUGl4ZWwgMiBYTCBCdWlsZFwvT1BEMS4xNzA4MTYuMDA0KSBBcHBsZVdlYktpdFwvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC84My4wLjQxMDMuMTE2IE1vYmlsZSBTYWZhcmlcLzUzNy4zNiIsImV4cCI6MTYyNDk3NTA3NSwidWlkIjoiNWVmOWYzNjNlYzI3MDAwMDkwMDAzYWIyIiwiYWNjb3VudCI6IjE1OTI2OTAwNjUzIn0.aPgUqu0jnsXVcQvD03xobxk446qBQ58rWX0RwXIGKjVCqPMtTjMhrM1q5OY9VPUh_Ue6HG_wxLh4Gq3zGBcmi4xywq8PrHVJZkvH4Yv0Pvw4_yo1MpTkLGrXEpye1TBNe6W13bh1cjPKGuCvk0hH_3NoqtcbN5ayuJOj0eSZNzo
Content-Type: application/x-www-form-urlencoded

### 获取每分钟的IP数量（ip）
GET http://127.0.0.1:5000/get_ip_num_by_minute
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhcGkubS5jb20iLCJpYXQiOjE1OTM0MzkwNzUsInN1YiI6Img1IiwiYXVkIjoiTW96aWxsYVwvNS4wIChMaW51eDsgQW5kcm9pZCA4LjAuMDsgUGl4ZWwgMiBYTCBCdWlsZFwvT1BEMS4xNzA4MTYuMDA0KSBBcHBsZVdlYktpdFwvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC84My4wLjQxMDMuMTE2IE1vYmlsZSBTYWZhcmlcLzUzNy4zNiIsImV4cCI6MTYyNDk3NTA3NSwidWlkIjoiNWVmOWYzNjNlYzI3MDAwMDkwMDAzYWIyIiwiYWNjb3VudCI6IjE1OTI2OTAwNjUzIn0.aPgUqu0jnsXVcQvD03xobxk446qBQ58rWX0RwXIGKjVCqPMtTjMhrM1q5OY9VPUh_Ue6HG_wxLh4Gq3zGBcmi4xywq8PrHVJZkvH4Yv0Pvw4_yo1MpTkLGrXEpye1TBNe6W13bh1cjPKGuCvk0hH_3NoqtcbN5ayuJOj0eSZNzo
Content-Type: application/x-www-form-urlencoded


### 获取IP请求数量最多的前50
GET http://127.0.0.1:5000/get_request_num_by_ip
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhcGkubS5jb20iLCJpYXQiOjE1OTM0MzkwNzUsInN1YiI6Img1IiwiYXVkIjoiTW96aWxsYVwvNS4wIChMaW51eDsgQW5kcm9pZCA4LjAuMDsgUGl4ZWwgMiBYTCBCdWlsZFwvT1BEMS4xNzA4MTYuMDA0KSBBcHBsZVdlYktpdFwvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC84My4wLjQxMDMuMTE2IE1vYmlsZSBTYWZhcmlcLzUzNy4zNiIsImV4cCI6MTYyNDk3NTA3NSwidWlkIjoiNWVmOWYzNjNlYzI3MDAwMDkwMDAzYWIyIiwiYWNjb3VudCI6IjE1OTI2OTAwNjUzIn0.aPgUqu0jnsXVcQvD03xobxk446qBQ58rWX0RwXIGKjVCqPMtTjMhrM1q5OY9VPUh_Ue6HG_wxLh4Gq3zGBcmi4xywq8PrHVJZkvH4Yv0Pvw4_yo1MpTkLGrXEpye1TBNe6W13bh1cjPKGuCvk0hH_3NoqtcbN5ayuJOj0eSZNzo
Content-Type: application/x-www-form-urlencoded




### 获取请求最多的 url
GET http://127.0.0.1:5000/get_request_num_by_url?type=init
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhcGkubS5jb20iLCJpYXQiOjE1OTM0MzkwNzUsInN1YiI6Img1IiwiYXVkIjoiTW96aWxsYVwvNS4wIChMaW51eDsgQW5kcm9pZCA4LjAuMDsgUGl4ZWwgMiBYTCBCdWlsZFwvT1BEMS4xNzA4MTYuMDA0KSBBcHBsZVdlYktpdFwvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC84My4wLjQxMDMuMTE2IE1vYmlsZSBTYWZhcmlcLzUzNy4zNiIsImV4cCI6MTYyNDk3NTA3NSwidWlkIjoiNWVmOWYzNjNlYzI3MDAwMDkwMDAzYWIyIiwiYWNjb3VudCI6IjE1OTI2OTAwNjUzIn0.aPgUqu0jnsXVcQvD03xobxk446qBQ58rWX0RwXIGKjVCqPMtTjMhrM1q5OY9VPUh_Ue6HG_wxLh4Gq3zGBcmi4xywq8PrHVJZkvH4Yv0Pvw4_yo1MpTkLGrXEpye1TBNe6W13bh1cjPKGuCvk0hH_3NoqtcbN5ayuJOj0eSZNzo
Content-Type: application/x-www-form-urlencoded



### 获取某个请求状态码的所有url
GET http://127.0.0.1:5000/get_request_num_by_status_code?code=502
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhcGkubS5jb20iLCJpYXQiOjE1OTM0MzkwNzUsInN1YiI6Img1IiwiYXVkIjoiTW96aWxsYVwvNS4wIChMaW51eDsgQW5kcm9pZCA4LjAuMDsgUGl4ZWwgMiBYTCBCdWlsZFwvT1BEMS4xNzA4MTYuMDA0KSBBcHBsZVdlYktpdFwvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC84My4wLjQxMDMuMTE2IE1vYmlsZSBTYWZhcmlcLzUzNy4zNiIsImV4cCI6MTYyNDk3NTA3NSwidWlkIjoiNWVmOWYzNjNlYzI3MDAwMDkwMDAzYWIyIiwiYWNjb3VudCI6IjE1OTI2OTAwNjUzIn0.aPgUqu0jnsXVcQvD03xobxk446qBQ58rWX0RwXIGKjVCqPMtTjMhrM1q5OY9VPUh_Ue6HG_wxLh4Gq3zGBcmi4xywq8PrHVJZkvH4Yv0Pvw4_yo1MpTkLGrXEpye1TBNe6W13bh1cjPKGuCvk0hH_3NoqtcbN5ayuJOj0eSZNzo
Content-Type: application/x-www-form-urlencoded

### 获取所有请求状态码
GET http://127.0.0.1:5000/get_request_num_by_status
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhcGkubS5jb20iLCJpYXQiOjE1OTM0MzkwNzUsInN1YiI6Img1IiwiYXVkIjoiTW96aWxsYVwvNS4wIChMaW51eDsgQW5kcm9pZCA4LjAuMDsgUGl4ZWwgMiBYTCBCdWlsZFwvT1BEMS4xNzA4MTYuMDA0KSBBcHBsZVdlYktpdFwvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC84My4wLjQxMDMuMTE2IE1vYmlsZSBTYWZhcmlcLzUzNy4zNiIsImV4cCI6MTYyNDk3NTA3NSwidWlkIjoiNWVmOWYzNjNlYzI3MDAwMDkwMDAzYWIyIiwiYWNjb3VudCI6IjE1OTI2OTAwNjUzIn0.aPgUqu0jnsXVcQvD03xobxk446qBQ58rWX0RwXIGKjVCqPMtTjMhrM1q5OY9VPUh_Ue6HG_wxLh4Gq3zGBcmi4xywq8PrHVJZkvH4Yv0Pvw4_yo1MpTkLGrXEpye1TBNe6W13bh1cjPKGuCvk0hH_3NoqtcbN5ayuJOj0eSZNzo
Content-Type: application/x-www-form-urlencoded

### 获取所有中国城市请求分布
GET http://127.0.0.1:5000/get_request_num_by_province
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhcGkubS5jb20iLCJpYXQiOjE1OTM0MzkwNzUsInN1YiI6Img1IiwiYXVkIjoiTW96aWxsYVwvNS4wIChMaW51eDsgQW5kcm9pZCA4LjAuMDsgUGl4ZWwgMiBYTCBCdWlsZFwvT1BEMS4xNzA4MTYuMDA0KSBBcHBsZVdlYktpdFwvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC84My4wLjQxMDMuMTE2IE1vYmlsZSBTYWZhcmlcLzUzNy4zNiIsImV4cCI6MTYyNDk3NTA3NSwidWlkIjoiNWVmOWYzNjNlYzI3MDAwMDkwMDAzYWIyIiwiYWNjb3VudCI6IjE1OTI2OTAwNjUzIn0.aPgUqu0jnsXVcQvD03xobxk446qBQ58rWX0RwXIGKjVCqPMtTjMhrM1q5OY9VPUh_Ue6HG_wxLh4Gq3zGBcmi4xywq8PrHVJZkvH4Yv0Pvw4_yo1MpTkLGrXEpye1TBNe6W13bh1cjPKGuCvk0hH_3NoqtcbN5ayuJOj0eSZNzo
Content-Type: application/x-www-form-urlencoded


### 获取每秒的请求量
GET http://127.0.0.1:5000/get_request_num_by_secends
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhcGkubS5jb20iLCJpYXQiOjE1OTM0MzkwNzUsInN1YiI6Img1IiwiYXVkIjoiTW96aWxsYVwvNS4wIChMaW51eDsgQW5kcm9pZCA4LjAuMDsgUGl4ZWwgMiBYTCBCdWlsZFwvT1BEMS4xNzA4MTYuMDA0KSBBcHBsZVdlYktpdFwvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC84My4wLjQxMDMuMTE2IE1vYmlsZSBTYWZhcmlcLzUzNy4zNiIsImV4cCI6MTYyNDk3NTA3NSwidWlkIjoiNWVmOWYzNjNlYzI3MDAwMDkwMDAzYWIyIiwiYWNjb3VudCI6IjE1OTI2OTAwNjUzIn0.aPgUqu0jnsXVcQvD03xobxk446qBQ58rWX0RwXIGKjVCqPMtTjMhrM1q5OY9VPUh_Ue6HG_wxLh4Gq3zGBcmi4xywq8PrHVJZkvH4Yv0Pvw4_yo1MpTkLGrXEpye1TBNe6W13bh1cjPKGuCvk0hH_3NoqtcbN5ayuJOj0eSZNzo
Content-Type: application/x-www-form-urlencoded

### 获取前50的请求量最高的ip
GET http://127.0.0.1:5000/get_request_num_by_ip
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhcGkubS5jb20iLCJpYXQiOjE1OTM0MzkwNzUsInN1YiI6Img1IiwiYXVkIjoiTW96aWxsYVwvNS4wIChMaW51eDsgQW5kcm9pZCA4LjAuMDsgUGl4ZWwgMiBYTCBCdWlsZFwvT1BEMS4xNzA4MTYuMDA0KSBBcHBsZVdlYktpdFwvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC84My4wLjQxMDMuMTE2IE1vYmlsZSBTYWZhcmlcLzUzNy4zNiIsImV4cCI6MTYyNDk3NTA3NSwidWlkIjoiNWVmOWYzNjNlYzI3MDAwMDkwMDAzYWIyIiwiYWNjb3VudCI6IjE1OTI2OTAwNjUzIn0.aPgUqu0jnsXVcQvD03xobxk446qBQ58rWX0RwXIGKjVCqPMtTjMhrM1q5OY9VPUh_Ue6HG_wxLh4Gq3zGBcmi4xywq8PrHVJZkvH4Yv0Pvw4_yo1MpTkLGrXEpye1TBNe6W13bh1cjPKGuCvk0hH_3NoqtcbN5ayuJOj0eSZNzo
Content-Type: application/x-www-form-urlencoded


### 获取某个ip 请求的urls
GET http://127.0.0.1:5000/get_request_urls_by_ip?ip=47.112.167.32
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhcGkubS5jb20iLCJpYXQiOjE1OTM0MzkwNzUsInN1YiI6Img1IiwiYXVkIjoiTW96aWxsYVwvNS4wIChMaW51eDsgQW5kcm9pZCA4LjAuMDsgUGl4ZWwgMiBYTCBCdWlsZFwvT1BEMS4xNzA4MTYuMDA0KSBBcHBsZVdlYktpdFwvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC84My4wLjQxMDMuMTE2IE1vYmlsZSBTYWZhcmlcLzUzNy4zNiIsImV4cCI6MTYyNDk3NTA3NSwidWlkIjoiNWVmOWYzNjNlYzI3MDAwMDkwMDAzYWIyIiwiYWNjb3VudCI6IjE1OTI2OTAwNjUzIn0.aPgUqu0jnsXVcQvD03xobxk446qBQ58rWX0RwXIGKjVCqPMtTjMhrM1q5OY9VPUh_Ue6HG_wxLh4Gq3zGBcmi4xywq8PrHVJZkvH4Yv0Pvw4_yo1MpTkLGrXEpye1TBNe6W13bh1cjPKGuCvk0hH_3NoqtcbN5ayuJOj0eSZNzo
Content-Type: application/x-www-form-urlencoded

### 从ua 获取爬虫信息
GET http://127.0.0.1:5000/get_spider_by_ua
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhcGkubS5jb20iLCJpYXQiOjE1OTM0MzkwNzUsInN1YiI6Img1IiwiYXVkIjoiTW96aWxsYVwvNS4wIChMaW51eDsgQW5kcm9pZCA4LjAuMDsgUGl4ZWwgMiBYTCBCdWlsZFwvT1BEMS4xNzA4MTYuMDA0KSBBcHBsZVdlYktpdFwvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC84My4wLjQxMDMuMTE2IE1vYmlsZSBTYWZhcmlcLzUzNy4zNiIsImV4cCI6MTYyNDk3NTA3NSwidWlkIjoiNWVmOWYzNjNlYzI3MDAwMDkwMDAzYWIyIiwiYWNjb3VudCI6IjE1OTI2OTAwNjUzIn0.aPgUqu0jnsXVcQvD03xobxk446qBQ58rWX0RwXIGKjVCqPMtTjMhrM1q5OY9VPUh_Ue6HG_wxLh4Gq3zGBcmi4xywq8PrHVJZkvH4Yv0Pvw4_yo1MpTkLGrXEpye1TBNe6W13bh1cjPKGuCvk0hH_3NoqtcbN5ayuJOj0eSZNzo
Content-Type: application/x-www-form-urlencoded

### 从ua 获取设备类型 pc端 和 移动端 对比曲线
GET http://127.0.0.1:5000/get_device_type_by_ua
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhcGkubS5jb20iLCJpYXQiOjE1OTM0MzkwNzUsInN1YiI6Img1IiwiYXVkIjoiTW96aWxsYVwvNS4wIChMaW51eDsgQW5kcm9pZCA4LjAuMDsgUGl4ZWwgMiBYTCBCdWlsZFwvT1BEMS4xNzA4MTYuMDA0KSBBcHBsZVdlYktpdFwvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lXC84My4wLjQxMDMuMTE2IE1vYmlsZSBTYWZhcmlcLzUzNy4zNiIsImV4cCI6MTYyNDk3NTA3NSwidWlkIjoiNWVmOWYzNjNlYzI3MDAwMDkwMDAzYWIyIiwiYWNjb3VudCI6IjE1OTI2OTAwNjUzIn0.aPgUqu0jnsXVcQvD03xobxk446qBQ58rWX0RwXIGKjVCqPMtTjMhrM1q5OY9VPUh_Ue6HG_wxLh4Gq3zGBcmi4xywq8PrHVJZkvH4Yv0Pvw4_yo1MpTkLGrXEpye1TBNe6W13bh1cjPKGuCvk0hH_3NoqtcbN5ayuJOj0eSZNzo
Content-Type: application/x-www-form-urlencoded

###
